[bindings.kotlin]
package_name = "com.iotzio.api"
android = false
kotlin_target_version = "2.0.0"

[bindings.swift]
module_name = "Com.Iotzio.Api"

[bindings.csharp]
namespace = "Com.Iotzio.Api"
access_modifier = "public"
