[package]
name = "api-functions"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
iotzio = { path = "../../iotzio" }
log = "0.4"
anyhow = "1.0"
thiserror = "2.0"
simple_logger = "5.0"
async-std = { version = "1.13", features = ["attributes"] }
